title: Status SysCorner
name: status_syscorner
description: "SysCorner Status Dashboard"
defaultLocale: en
baseUrl: "https://status.syscorner.com"
locales:
  - code: en
    iso: en-US
    name: English
    file: en.json
content:
  frontMatterFormat: json
  systems:
    - web
    - services
    - mirrorsfr
    - mirrorsnl