name: "Statusfy Incident"
on:
  issue_comment:
  issues:
    types: [opened, edited, closed, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for build to succeed
      uses: fountainhead/action-wait-for-check@v1.0.0
      id: wait-for-build
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Statusfy Incident
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - name: Do something with a passing build
      if: steps.wait-for-build.outputs.conclusion == 'success'
    - name: Do something with a failing build
      if: steps.wait-for-build.outputs.conclusion == 'failure'
      
    - uses: actions/checkout@v1
    - name: Generate incident
      uses: devkanro/setup-statusfy@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
    - name: Build the static site.
      run: |
        npm install
        npm run generate
    - name: Publish the static site to GitHub Pages.
      uses: jamesives/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
